name: Build and Deploy to Web App

on:
  workflow_dispatch: # Manual trigger

env:
  IMAGE_NAME: "gh-bphattersportal"
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Set your Docker Hub username as a GitHub secret
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Set your Docker Hub password as a GitHub secret
  DOCKER_HUB_REGISTRY: "docker.io/${{ secrets.DOCKER_USERNAME }}"
  AZURE_WEBAPP_NAME: "bp-hatters-portal"
  AZURE_RG_NAME: "RG-BP-HATTERS-PORTAL"

jobs:
  restricted-job:
    runs-on: ubuntu-latest
    if: github.actor == 'OfficialMabz' # Replace with your GitHub username
    steps:
      - name: Display message
        run: echo "This job is running only for the repository owner."

  build-and-push:
    runs-on: ubuntu-latest
    needs: restricted-job
    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t $DOCKER_HUB_REGISTRY/$IMAGE_NAME:${{ github.run_id }} .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_HUB_REGISTRY/$IMAGE_NAME:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # Step 1: Log in to Azure CLI
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Set your Azure credentials as a GitHub secret

      # Step 2: Deploy to Azure Web App
      - name: Deploy image to Azure Web App
        run: |
          az webapp config container set \
            --name $AZURE_WEBAPP_NAME \
            --resource-group $AZURE_RG_NAME \
            --docker-custom-image-name $DOCKER_HUB_REGISTRY/$IMAGE_NAME:${{ github.run_id }} \
            --docker-registry-server-url https://index.docker.io/v1/ \
            --docker-registry-server-user $DOCKER_USERNAME \
            --docker-registry-server-password $DOCKER_PASSWORD
